on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache build
        uses: Swatinem/rust-cache@v2

      - run: cargo check

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache build
        uses: Swatinem/rust-cache@v2

      - run: cargo fmt --check

  clippy:
    name: cargo clippy / ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: Cache build
        uses: Swatinem/rust-cache@v2

      - run: cargo clippy -- -Dclippy::correctness -Wclippy::suspicious -Dclippy::complexity -Dclippy::perf -Dclippy::style

  test-toolchains:
    name: cargo test / ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cache build
        uses: Swatinem/rust-cache@v2

      - run: cargo test --workspace

  test-os:
    name: cargo test / ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache build
        uses: Swatinem/rust-cache@v2

      - run: cargo test --workspace
